//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Asiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiento()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int CodAsiento { get; set; }
        [Required]
        [Display(Name = "Descripción del asiento")]
        public string DescripcionAsiento { get; set; }
        [Required]
        [Display(Name = "Sala (ID)")]
        public Nullable<int> CodSala { get; set; }
        [Required]
        [Display(Name = "Tipo de asiento")]
        public Nullable<int> TipoAsiento { get; set; }
        [Required]
        [Display(Name = "Disponibilidad")]
        public Nullable<bool> Disponible { get; set; }
    
        public virtual Sala Sala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
