//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Funcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcion()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int CodFuncion { get; set; }
        [Required]
        [Display(Name = "Hora de inicio")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> HoraInicio { get; set; }
        [Required]
        [Display(Name = "Hora de finalización")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> HoraFin { get; set; }
        [Required]
        [Display(Name = "Película (ID)")]
        public Nullable<int> CodPelicula { get; set; }
        [Required]
        [Display(Name = "Fecha de la función")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FechaFuncion { get; set; }
        [Required]
        [Display(Name ="Precio de la función")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> Precio { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
