//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Interprete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Interprete()
        {
            this.Protagonista = new HashSet<Protagonista>();
        }
    
        public int CodInterprete { get; set; }
        [Required]
        [Display(Name = "Apellido paterno del intérprete")]
        public string Paterno { get; set; }
        [Required]
        [Display(Name = "Apellido materno del intérprete")]
        public string Materno { get; set; }
        [Required]
        [Display(Name = "Nombres del intérprete")]
        public string Nombres { get; set; }
        [Required]
        [Display(Name = "Nacionalidad del intérprete")]
        public string Nacionalidad { get; set; }
        public string Foto { get; set; }
        public string Bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Protagonista> Protagonista { get; set; }
    }
}
