//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido
    {
        public int CodPedido { get; set; }
        [Required]
        [Display(Name = "Descripción del pedido")]
        public string Descripcion { get; set; }
        [Required]
        [Display(Name = "Ticket (ID)")]
        public Nullable<int> CodTicket { get; set; }
    }
}
