//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreCine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pelicula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelicula()
        {
            this.CinePelicula = new HashSet<CinePelicula>();
            this.Funcion = new HashSet<Funcion>();
            this.Protagonista = new HashSet<Protagonista>();
        }
    
        public int CodPelicula { get; set; }
        [Required]
        [Display(Name = "Nombre de la película")]
        public string NombrePelicula { get; set; }
        [Required]
        [Display(Name = "Duración de la película")]
        public string Duracion { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de estreno")]
        public Nullable<System.DateTime> FechaEstreno { get; set; }
        [Required]
        [Display(Name = "Director (ID)")]
        public Nullable<int> CodDirector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CinePelicula> CinePelicula { get; set; }
        public virtual Director Director { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcion> Funcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Protagonista> Protagonista { get; set; }
    }
}
